# Generated by Django 6.0.3 on 2026-03-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('col', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado temporariamente'), ('purchased', 'Comprado')], default='available', max_length=10)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=20, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
